version: 0.2
phases:
    pre_build:
        commands:
    build:
        commands:
            - dotnet restore
            - dotnet publish Council.DiscordBot.sln -c Release -r linux-x64 --self-contained true /m:1 -o build
    post_build:
        commands:
artifacts:
    files:
        - "build/*.*"
        - "serverless.yml"
    discard-paths: yes