version: 0.2
phases:
    pre_build:
        commands:
    build:
        commands:
            - dotnet restore
            - dotnet publish Council.DiscordBot.sln -c Release -r linux-x64 --self-contained true
    post_build:
        commands:
artifacts:
    files:
        - "buildinfo.xml"
        - "bin/*.dll"
        - "bin/*.json"
        - "serverless.template"
    discard-paths: yes